### ISSUE TITLE
User type is set as "admin" while it should be set as "customer" when sign up parameter 'is_vendor' is set to empty string.

### ISSUE THREAD

**Issue by AsenaKarolin** [bounswe/bounswe2020group1#270]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

When a new user is created with a request where the 'is_vendor' parameter is an empty string, the user type should be set as "customer". (As stated in the endpoint documentation)

# Current Behavior

When a new user is created with a request where the 'is_vendor' parameter is an empty string, the user type is set as "admin".

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a user where the is_vendor parameter is given as an empty string.
2. Sign in and check the response data of the sign in request.

## Context

* Request sent with: Axios
* Operating System: Windows

**Comment by onurkilic2301** [comment]
I reproduced the bug and found out that the problem arised from a user added via Django shell manually. I updated the user and the code itself should not allow the bug to happen again in the current form since the validity checks are done properly while using the signup endpoint.

However if the functionality still does not work as expected, I will take a second look at the problem.
